name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: DockerHub Login
      env:
        DOCKER_HUB_USER: ${{secrets.DOCKER_HUB_USER}}
        DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      run: |
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD

    - name: Build Docker Image
      run: |
        docker build -t vicseore/docker-graphql:0.0.1 .

    - name: Push Docker Image
      run: |
        docker push vicseore/docker-graphql:0.0.1
       

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
