name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}"
      id: version
        
    - name: DockerHub Login
      env:
        DOCKER_HUB_USER: ${{secrets.DOCKER_HUB_USER}}
        DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
        echo "New Version: $NEW_VERSION!!!!!"

    - name: Build Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t vicseore/docker-graphql:$NEW_VERSION .
        docker build -t vicseore/docker-graphql:latest .

    - name: Push Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push vicseore/docker-graphql:$NEW_VERSION
        docker push vicseore/docker-graphql:latest
      
